import { IStatusList } from 'src/app/modules/components/Settings/status-list/status-list.component';
import { ICondition } from 'src/app/modules/Models/Subscriptor/.subscription/interface/IConditions';
import { ISubscriptionStatus } from 'src/app/modules/Models/Subscriptor/.subscription/interface/ISubscriptionStatus';

export const statusManagerList: IStatusList[] = [
  {
    status: ISubscriptionStatus.DEUDA1,
    color: 'bg-red-500',
    condition: ICondition.HABILITADO,
    message: 'Debe 1 pago',
    icon: 'done',
    id: 1,
  },
  {
    status: ISubscriptionStatus.DEUDA2,
    color: 'bg-red-500',
    condition: ICondition.INHABILITADO,
    message: 'Debe 2 pagos',
    icon: 'done',
    id: 2,
  },
  {
    status: ISubscriptionStatus.DEUDA3,
    color: 'bg-red-500',
    condition: ICondition.INHABILITADO,
    message: 'Debe 3 pagos',
    icon: 'done',
    id: 3,
  },
  {
    status: ISubscriptionStatus.DEUDA4,
    color: 'bg-red-500',
    condition: ICondition.INHABILITADO,
    message: 'Debe 4 pagos',
    icon: 'done',
    id: 4,
  },
  {
    status: ISubscriptionStatus.MOROSO1,
    color: 'bg-red-500',
    condition: ICondition.INHABILITADO,
    message: 'Debe mas de 4 pagos',
    icon: 'done',
    id: 5,
  },
  {
    status: ISubscriptionStatus.MOROSO2,
    color: 'bg-red-500',
    condition: ICondition.INHABILITADO,
    message: 'Debe mas de 4 pagos',
    icon: 'done',
    id: 6,
  },
  {
    status: ISubscriptionStatus.CONGELADO,
    color: 'bg-slate-500',
    condition: ICondition.INHABILITADO,
    message: 'Tiene la suscripcion congelada',
    icon: 'done',
    id: 7,
  },
  {
    status: ISubscriptionStatus.PENDIENTE,
    color: 'bg-yellow-500',
    condition: ICondition.INHABILITADO,
    message: 'No tiene suscripcion',
    icon: 'done',
    id: 8,
  },
  {
    status: ISubscriptionStatus.ACTIVO,
    color: 'bg-green-500',
    condition: ICondition.HABILITADO,
    message: 'Puede pasar!',
    icon: 'done',
    id: 9,
  },
  {
    status: ISubscriptionStatus.ALTA,
    color: 'bg-yellow-500',
    condition: ICondition.INHABILITADO,
    message: 'Necesita pagar la primer cuota / matricula.',
    icon: 'done',
    id: 10,
  },
  {
    status: ISubscriptionStatus.PRUEBA,
    color: 'bg-blue-500',
    condition: ICondition.HABILITADO,
    message: 'Esta en el periodo de prueba',
    icon: 'done',
    id: 11,
  },
];
